server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能
      #          lower-case-service-id: true
      routes:
        - id: payment_routh
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service #此处如果有问题，请注意依赖spring-cloud-starter-netflix-eureka-client依赖不能错
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2020-03-26T08:40:06.636+08:00[Asia/Shanghai]
#            - Query=username,\d+   #username 要为正数  ？username=31
#            - Cookie=username,waitwind     #curl http://localhost:9527/payment/lb --cookie "username=waitwind"  在cmd窗口访问该路径
#            - Header=X-Request-Id,\d+    #请求头要有X-Request-Id，并且值为正数 #curl http://localhost:9527/payment/lb --cookie -H "X-Request-Id:123"
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka
#logging:
#  level:
#    root: debug
